packages:
  - application/*
  - packages/*
  - tooling/*
  
catalog:
  '@tanstack/react-query': ^5.77.2
  eslint: ^9.27.0
  prettier: ^3.5.3
  tailwindcss: ^3.4.17
  typescript: ^5.8.3
  zod: ^3.25.32

catalogs:
  react19:
    react: 19.1.0
    react-dom: 19.1.0
    '@types/react': ^19.1.6
    '@types/react-dom': ^19.1.5
