packages:
  - application/*
  - packages/*
  - tooling/*
catalog:
  '@tanstack/react-query': ^5.69.0
  eslint: ^9.23.0
  prettier: ^3.5.3
  tailwindcss: ^3.4.17
  typescript: ^5.8.2
  zod: ^3.24.2
catalogs:
  react19:
    react: 19.0.0
    react-dom: 19.0.0
    '@types/react': ^19.0.10
    '@types/react-dom': ^19.0.4

onlyBuiltDependencies:
  - better-sqlite3
  
ignoredBuiltDependencies:
  - bufferutil
  - core-js-pure
  - esbuild
  - sharp
