packages:
  - application/*
  - packages/*
  - tooling/*

catalog:
  "@tanstack/react-query": ^5.62.11
  eslint: ^9.17.0
  prettier: ^3.4.2
  tailwindcss: ^3.4.17
  typescript: ^5.7.2
  zod: ^3.24.1

catalogs:
  react19:
    react: 19.0.0
    react-dom: 19.0.0
    "@types/react": ^19.0.2
    "@types/react-dom": ^19.0.2
