packages:
  - application/*
  - packages/*
  - tooling/*

catalog:
  '@tanstack/react-query': ^5.82.0
  eslint: ^9.30.1
  prettier: ^3.6.2
  tailwindcss: ^3.4.17
  typescript: ^5.8.3
  zod: ^4.0.2

catalogs:
  react19:
    react: 19.1.0
    react-dom: 19.1.0
    '@types/react': ^19.1.8
    '@types/react-dom': ^19.1.6
