packages:
  - application/*
  - packages/*
  - tooling/*

catalog:
  '@tanstack/react-query': ^5.90.11
  eslint: ^9.39.1
  prettier: ^3.7.4
  tailwindcss: ^3.4.17
  typescript: ^5.9.3
  zod: ^4.1.13

catalogs:
  react19:
    '@types/react': ^19.2.7
    '@types/react-dom': ^19.2.3
    react: ^19.2.1
    react-dom: ^19.2.1
