packages:
  - application/*
  - packages/*
  - tooling/*

catalog:
  "@tanstack/react-query": ^5.66.9
  eslint: ^9.21.0
  prettier: ^3.5.2
  tailwindcss: ^3.4.17
  typescript: ^5.7.3
  zod: ^3.24.2

catalogs:
  react19:
    react: 19.0.0
    react-dom: 19.0.0
    "@types/react": ^19.0.10
    "@types/react-dom": ^19.0.4
