packages:
  - application/*
  - packages/*
  - tooling/*

catalog:
  "@tanstack/react-query": ^5.64.1
  eslint: ^9.18.0
  prettier: ^3.4.2
  tailwindcss: ^3.4.17
  typescript: ^5.7.3
  zod: ^3.24.1

catalogs:
  react19:
    react: 19.0.0
    react-dom: 19.0.0
    "@types/react": ^19.0.7
    "@types/react-dom": ^19.0.3
