packages:
  - application/*
  - packages/*
  - tooling/*
  
catalog:
  '@tanstack/react-query': ^5.74.4
  eslint: ^9.25.0
  prettier: ^3.5.3
  tailwindcss: ^3.4.17
  typescript: ^5.8.3
  zod: ^3.24.3

catalogs:
  react19:
    react: 19.1.0
    react-dom: 19.1.0
    '@types/react': ^19.1.2
    '@types/react-dom': ^19.1.2

onlyBuiltDependencies:
  - better-sqlite3
  
ignoredBuiltDependencies:
  - bufferutil
  - core-js-pure
  - esbuild
  - sharp
