packages:
  - application/*
  - packages/*
  - tooling/*

catalog:
  '@tanstack/react-query': ^5.90.2
  eslint: ^9.36.0
  prettier: ^3.6.2
  tailwindcss: ^3.4.17
  typescript: ^5.8.3
  zod: ^4.1.11

catalogs:
  react19:
    '@types/react': ^19.1.16
    '@types/react-dom': ^19.1.9
    react: ^19.1.1
    react-dom: ^19.1.1
